name: Build project and run Lighthouse CI
on: [push]
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm install

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.5.x

      - name: Build website
        run: npm run build
        
      - name: run Lighthouse CI
        run: lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
